trigger: none # disable CI trigger i.e. only run on PRs

pr: # enable PR trigger for all branches i.e. run this pipeline on all PR create/updates.
  branches:
    include:
      - '*'

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
## -- Build app -- ##
  - template: templates/build-app-template.yml
    parameters:
      stageName: 'BuildApp'
      displayName: 'Build App'
## -- Build app -- ##

  - stage: DeployAppCypress
    displayName: Deploy App Cypress
    jobs:
      - deployment: cypressdeploy
        displayName: Deploy App Cypress
        pool:
          name: Azure Pipelines
          vmImage: 'ubuntu-latest'
        environment: CYPRESS
        strategy:
          runOnce:
            preDeploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    targetPath: '$(Pipeline.Workspace)'
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 's203d.azdo.deployment'
                    appType: 'webApp'
                    WebAppName: 'ece-dev-as-cypress'
                    packageForLinux: '$(Pipeline.Workspace)/checkYourEligibilityFrontEnd/CheckYourEligibility.FrontEnd.zip'
                - task: Bash@3
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkYourEligibilityFrontEnd/tests
                      npm install
                - task: Bash@3
                  displayName: 'RunTests'
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkYourEligibilityFrontEnd/tests
                      export CYPRESS_BASE_URL="$(CYPRESS_BASE_URL_CYPRESS)"
                      export CYPRESS_AUTHORIZATION_HEADER="$(AUTHORIZATION_HEADER)"
                      export CYPRESS_AUTH_USERNAME="$(AUTH_USERNAME)"
                      export CYPRESS_AUTH_PASSWORD="$(AUTH_PASSWORD)"
                      export CYPRESS_ONEGOV_EMAIL="$(ONEGOV_EMAIL)"
                      export CYPRESS_ONEGOV_PASSWORD="$(ONEGOV_PASSWORD)"
                      npm run parentE2e:electron
                - task: Bash@3
                  condition: always()
                  displayName: 'Generate report'
                  inputs:
                    targetType: inline
                    script: |
                      cd $(Pipeline.Workspace)/checkYourEligibilityFrontEnd/tests
                      npm run combine:reports
                - task: PublishBuildArtifacts@1
                  displayName: 'Publish Cypress Screenshot Files'
                  condition: failed()
                  inputs:
                    PathtoPublish: '$(Pipeline.Workspace)/checkYourEligibilityFrontEnd/tests/cypress/screenshots/'
                    ArtifactName: 'screenshots'
                - task: PublishTestResults@2
                  condition: always()
                  displayName: 'Publish test results'
                  inputs:
                    testResultsFiles: '**/combined-report.xml'
                    searchFolder: '$(Pipeline.Workspace)/checkYourEligibilityFrontEnd/tests'