describe('Admin FSM Reporting', () => {
    const today = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
    });

    beforeEach(() => {
        cy.checkSession('basic');
        cy.visit((Cypress.config().baseUrl ?? "") + "/home");
        cy.wait(1);
        cy.get('.govuk-caption-l').should('include.text', 'Manchester City Council');
    });

    it('Can generate FSM report with new date range and check type options', () => {
        
        cy.contains('a.dfe-card-link--header', 'Reports').click();
        cy.get('.govuk-heading-l').should('include.text', 'Report history');

        cy.contains('Generate report').click();
        cy.url().should('include', '/EligibilityCheckReporting/Create_Report');

        cy.get("#StartDate\\.Day").should('not.exist');
        cy.get("#StartDate\\.Month").should('not.exist');
        cy.get("#StartDate\\.Year").should('not.exist');
        cy.get("#EndDate\\.Day").should('not.exist');
        cy.get("#EndDate\\.Month").should('not.exist');
        cy.get("#EndDate\\.Year").should('not.exist');

        cy.get('select[name="DateRange"]').should('be.visible');
        cy.get('select[name="DateRange"]').find('option').should('have.length', 1);
        cy.get('select[name="DateRange"]').find('option').should('contain.text', 'Last 30 days');

        cy.get('select[name="CheckType"]').should('be.visible');
        cy.get('select[name="CheckType"]').find('option').should('have.length', 3);
        cy.get('select[name="CheckType"]').find('option').should('contain.text', 'All checks');
        cy.get('select[name="CheckType"]').find('option').should('contain.text', 'Individual checks');
        cy.get('select[name="CheckType"]').find('option').should('contain.text', 'Batch checks');

        cy.contains('Generate report').click();

        cy.url({ timeout: 80000 }).should('include', '/EligibilityCheckReporting/Reports');

        cy.get('.govuk-table').should('be.visible');
        cy.get('.govuk-table tbody tr').should('have.length.greaterThan', 0);

        // The latest report should be at the top
        cy.get('.govuk-table tbody tr:first-child').within(() => {
            // Check that the first column has today's date
            cy.get('td:first-child').should('contain.text', today);
        });
    });

    it('Can view historical reports on reports page', () => {
        cy.contains('a.dfe-card-link--header', 'Reports').click();
        cy.get('.govuk-heading-l').should('include.text', 'Report history');

        cy.get('.govuk-table__head').within(() => {
            cy.contains('th', 'Report generated').should('be.visible');
            cy.contains('th', 'Start date').should('be.visible');
            cy.contains('th', 'End date').should('be.visible');
            cy.contains('th', 'Generated by').should('be.visible');
            cy.contains('th', 'Number of results').should('be.visible');
            cy.contains('th', 'Status').should('be.visible');
        });

        cy.get('.govuk-table tbody tr').each(($row) => {
            cy.wrap($row).within(() => {
                cy.get('td').then(($cells) => {
                    const statusCell = $cells[$cells.length - 2]; // Status is second to last
                    const resultsCell = $cells[4]; // Number of results column
                    const statusText = statusCell.textContent;

                    if (statusText.includes('Complete')) {
                        cy.contains('a', 'Download report').should('be.visible');
                        cy.contains('a', 'Delete').should('be.visible');
                    }     
                });
            });
        });
        cy.get('nav.govuk-pagination').should('be.visible');
     });
    it('Can delete a report from the reports page', () => {
        cy.contains('a.dfe-card-link--header', 'Reports').click();
        cy.get('.govuk-heading-l').should('include.text', 'Report history');
        cy.get('.govuk-table tbody tr').first().within(() => {
            cy.contains('a', 'Delete').click();
        });
        cy.url().should('include', '/EligibilityCheckReporting/Delete_Report_Confirmation');
        cy.contains('button', 'Delete report').click();
        cy.url({ timeout: 80000 }).should('include', '/EligibilityCheckReporting/Reports');
    });
});
